apiVersion: v2
description: A Content Security Policy violation collector
name: csp-collector
type: application
version: 0.0.0
appVersion: "0.0.0"
home: https://github.com/jacobbednarz/go-csp-collector
sources:
  - https://github.com/jacobbednarz/go-csp-collector
maintainers:
  - name: jacobbednarz
    url: https://github.com/jacobbednarz
